Update pipeliines

diff --git a/.github/workflows/build-and-publish-backend-release.yml b/.github/workflows/build-and-publish-backend-release.yml
--- a/.github/workflows/build-and-publish-backend-release.yml
+++ b/.github/workflows/build-and-publish-backend-release.yml
@@ -1,9 +1,9 @@
-name: Build & Test Backend for Development, Publish PreRelease Version
+name: Build & Test Backend for Production, Publish Release Version
 
 on:
   push:
     branches:
-      - dev
+      - main
     paths:
       - 'src/**'
 
@@ -15,7 +15,7 @@ env:
 
 jobs:
   build_and_test:
-    timeout-minutes: 10
+    timeout-minutes: 20
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -32,9 +32,12 @@ jobs:
       - name: Build
         run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
 
+      - name: Test
+        run: dotnet test ${{ env.TESTS_SOLUTION_PATH }} --verbosity normal
+
   publish_prerelease:
     needs: build_and_test
-    timeout-minutes: 20
+    timeout-minutes: 10
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -75,20 +78,10 @@ jobs:
               exit 1
             fi
 
-            echo "Current version of package $PACKAGE_ID is $VERSION"
-
             # Extract the major, minor, patch and alpha numbers
             MAJOR=$(echo $VERSION | cut -d '.' -f1)
             MINOR=$(echo $VERSION | cut -d '.' -f2)
             PATCH=$(echo $VERSION | cut -d '.' -f3 | grep -o '^[0-9]*')
-            ALPHA_SUFFIX=$(echo $VERSION | grep -o '[a-zA-Z]*')
-            ALPHA_NUMBER=$(echo $VERSION | grep -o '[0-9]*$')
-
-            # Check if the alpha suffix and alpha number exist
-            if [[ -z "$ALPHA_SUFFIX" || -z "$ALPHA_NUMBER" ]]; then
-              echo "Error: Package $PACKAGE_ID is invalid, because Version does not have an alpha suffix and alpha number"
-              exit 1
-            fi
 
             # Check if the major version matches the .NET version
             if [[ "$MAJOR" != "$DOTNET_MAJOR_VERSION" ]]; then
@@ -110,50 +103,31 @@ jobs:
 
               # Validate current version against the latest version
               if echo $LATEST_VERSION | grep -q 'alpha'; then
-
-                if [[ $MINOR -lt $LATEST_MINOR || ($MINOR -eq $LATEST_MINOR && $PATCH -lt $LATEST_PATCH) ]]; then
-                  echo "Error: Package $PACKAGE_ID is invalid, because either the minor or patch version is not equal or greater than the latest version"
-                  exit 1
+                # If there's an alpha version, current version should match all major, minor, patch numbers
+                if [[ $MAJOR -ne $LATEST_MAJOR || $MINOR -ne $LATEST_MINOR || $PATCH -ne $LATEST_PATCH ]]; then
+                echo "Error: Package $PACKAGE_ID is invalid, because current version does not match the latest alpha version"
+                exit 1
                 fi
-      
-                if [[ $MAJOR -gt $LATEST_MAJOR || $MINOR -gt $LATEST_MINOR ]]; then
-                  if [[ $ALPHA_NUMBER -ne 0 ]]; then
-                    echo "Error: Package $PACKAGE_ID is invalid, because it's a new major or minor version and the alpha number is not 0"
-                    exit 1
-                  fi
-                else
-                  LATEST_ALPHA_NUMBER=$(echo $LATEST_VERSION | grep -oP 'alpha.\K\d+')
-                  if [[ $ALPHA_NUMBER -ne $((LATEST_ALPHA_NUMBER + 1)) ]]; then
-                    echo "Error: Package $PACKAGE_ID is invalid, because current alpha number is not one above the latest alpha number"
-                    exit 1
-                  fi
-                fi
-
               else
-
-                if [[ $MINOR -ne $((LATEST_MINOR + 1)) && $PATCH -ne $((LATEST_PATCH + 1)) ]]; then
-                  echo "Error: Package $PACKAGE_ID is invalid, because either the minor or patch version is not one higher than the latest version"
-                  exit 1
-                fi
-
-                if [[ $ALPHA_NUMBER -ne 0 ]]; then
-                  echo "Error: Package $PACKAGE_ID is invalid, because current alpha number is not 0"
-                  exit 1
-                fi
-
-              fi
-            else
-              if [[ $MINOR -ne 0 || $PATCH -ne 0 || $ALPHA_NUMBER -ne 0 ]]; then
-                echo "Error: Package $PACKAGE_ID is invalid, because current version is not $DOTNET_MAJOR_VERSION.0.0-alpha.0"
+                # If the alpha version wasn't released, release version shouldn't be published
+                echo "Error: Package $PACKAGE_ID is invalid, because the alpha version wasn't released"
                 exit 1
               fi
+            else 
+              echo "Error: Package $PACKAGE_ID is invalid, first version should be an alpha version"
+              exit 1
             fi
 
+            # Calculate current release version without alpha suffix
+            RELEASE_VERSION="${MAJOR}.${MINOR}.${PATCH}"
+
+            echo "Current release version of package $PACKAGE_ID is $RELEASE_VERSION"
+
             # Pack the project with the new version
-            echo "Packing project $PACKAGE_ID with version $VERSION"
-            dotnet pack $CS_PROJ -c Release -o ./nupkgs /p:PackageVersion=$VERSION
+            echo "Packing project $PACKAGE_ID with version $RELEASE_VERSION"
+            dotnet pack $CS_PROJ -c Release -o ./nupkgs /p:PackageVersion=$RELEASE_VERSION
     
             # Push the package to NuGet
-            echo "Pushing package ${PACKAGE_ID}.${VERSION}.nupkg"
-            dotnet nuget push "./nupkgs/${PACKAGE_ID}.${VERSION}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --no-service-endpoint
+            echo "Pushing package ${PACKAGE_ID}.${RELEASE_VERSION}.nupkg"
+            dotnet nuget push "./nupkgs/${PACKAGE_ID}.${RELEASE_VERSION}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --no-service-endpoint
           done
