Update pipeline

diff --git a/.github/workflows/build-and-publish-backend-prerelease.yml b/.github/workflows/build-and-publish-backend-prerelease.yml
--- a/.github/workflows/build-and-publish-backend-prerelease.yml
+++ b/.github/workflows/build-and-publish-backend-prerelease.yml
@@ -71,7 +71,7 @@ jobs:
             # Extract Version
             VERSION=$(grep '<Version>' "$CS_PROJ" | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
             if [ -z "$VERSION" ]; then
-              echo "Error: Skipped package $PACKAGE_ID, because Version is not specified"
+              echo "Error: Package $PACKAGE_ID is invalid, because Version is not specified"
               exit 1
             fi
 
@@ -86,13 +86,13 @@ jobs:
 
             # Check if the alpha suffix and alpha number exist
             if [[ -z "$ALPHA_SUFFIX" || -z "$ALPHA_NUMBER" ]]; then
-              echo "Error: Skipped package $PACKAGE_ID, because Version does not have an alpha suffix and alpha number"
+              echo "Error: Package $PACKAGE_ID is invalid, because Version does not have an alpha suffix and alpha number"
               exit 1
             fi
 
             # Check if the major version matches the .NET version
             if [[ "$MAJOR" != "$DOTNET_MAJOR_VERSION" ]]; then
-              echo "Error: Skipped package $PACKAGE_ID, because of major version mismatch. Expected major version: $DOTNET_MAJOR_VERSION, but found $MAJOR"
+              echo "Error: Package $PACKAGE_ID is invalid, because of major version mismatch. Expected major version: $DOTNET_MAJOR_VERSION, but found $MAJOR"
               exit 1
             fi
 
@@ -112,20 +112,25 @@ jobs:
               if echo $LATEST_VERSION | grep -q 'alpha'; then
 
                 if [[ $MINOR -lt $LATEST_MINOR || ($MINOR -eq $LATEST_MINOR && $PATCH -lt $LATEST_PATCH) ]]; then
-                  echo "Error: Skipped package $PACKAGE_ID, because either the minor or patch version is not equal or greater than the latest version"
+                  echo "Error: Package $PACKAGE_ID is invalid, because either the minor or patch version is not equal or greater than the latest version"
                   exit 1
                 fi
 
                 LATEST_ALPHA_NUMBER=$(echo $LATEST_VERSION | grep -oP 'alpha.\K\d+')
                 if [[ $ALPHA_NUMBER -ne $((LATEST_ALPHA_NUMBER + 1)) ]]; then
-                  echo "Error: Skipped package $PACKAGE_ID, because current alpha number is not one above the latest alpha number"
+                  echo "Error: Package $PACKAGE_ID is invalid, because current alpha number is not one above the latest alpha number"
                   exit 1
                 fi
                
               else
 
                 if [[ $MINOR -ne $((LATEST_MINOR + 1)) && $PATCH -ne $((LATEST_PATCH + 1)) ]]; then
-                  echo "Error: Skipped package $PACKAGE_ID, because either the minor or patch version is not one higher than the latest version"
+                  echo "Error: Package $PACKAGE_ID is invalid, because either the minor or patch version is not one higher than the latest version"
+                  exit 1
+                fi
+
+                if [[ $ALPHA_NUMBER -ne 0 ]]; then
+                  echo "Error: Package $PACKAGE_ID is invalid, because current alpha number is not 0"
                   exit 1
                 fi
 
